baseURL = 'https://me.zzek.cn'
languageCode = 'en-us'
title = '月牙博客'
theme = "techlab"
hasCJKLanguage = true


[menu]
[[menu.main]]
  name = '文章列表'
  url = '/all-posts/'
  weight = 1
[[menu.main]]
  name = '关于'
  url = '/about/'
  weight = 2
[[menu.main]]
  name = 'RSS'
  url = '/index.xml'
  weight = 3

[params]
  description = "月牙博客"
  includeFooter = true
  [params.social]
    Email = "vlikuiv@163.com"
    Github = "https://github.com/ilikui"
    Bilibili = ""
    Linkedin = ""
  [params.valine]
    enable = true
    appId = '9K4ZO5juSBzjbjlOaMY3vr6y-MdYXbMMI'
    appKey = 'AD7LdfH3AhSDumMbN5Sma4k9'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mm'
    placeholder = '说点什么吧...'
    visitor = true	

[taxonomies]
  tag = "tags"
  example = "life"
